/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'
import { Route as ChatsThreadIdRouteImport } from './routes/chats/$threadId'
import { Route as ApiAssetsAssetIdRouteImport } from './routes/api/assets/$assetId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiReviewsSyncRouteImport } from './routes/api/reviews/sync'
import { Route as ApiCardChatsThreadIdStreamRouteImport } from './routes/api/card-chats/$threadId/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsThreadIdRoute = ChatsThreadIdRouteImport.update({
  id: '/chats/$threadId',
  path: '/chats/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsAssetIdRoute = ApiAssetsAssetIdRouteImport.update({
  id: '/api/assets/$assetId',
  path: '/api/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsSyncRoute = ApiReviewsSyncRouteImport.update({
  id: '/api/reviews/sync',
  path: '/api/reviews/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardChatsThreadIdStreamRoute =
  ApiCardChatsThreadIdStreamRouteImport.update({
    id: '/api/card-chats/$threadId/stream',
    path: '/api/card-chats/$threadId/stream',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/chats/$threadId': typeof ChatsThreadIdRoute
  '/chats/': typeof ChatsIndexRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/reviews/sync': typeof ApiReviewsSyncRoute
  '/api/card-chats/$threadId/stream': typeof ApiCardChatsThreadIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/chats/$threadId': typeof ChatsThreadIdRoute
  '/chats': typeof ChatsIndexRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/reviews/sync': typeof ApiReviewsSyncRoute
  '/api/card-chats/$threadId/stream': typeof ApiCardChatsThreadIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/chats/$threadId': typeof ChatsThreadIdRoute
  '/chats/': typeof ChatsIndexRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/reviews/sync': typeof ApiReviewsSyncRoute
  '/api/card-chats/$threadId/stream': typeof ApiCardChatsThreadIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/progress'
    | '/settings'
    | '/topics'
    | '/chats/$threadId'
    | '/chats/'
    | '/api/assets/$assetId'
    | '/api/auth/$'
    | '/api/reviews/sync'
    | '/api/card-chats/$threadId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/progress'
    | '/settings'
    | '/topics'
    | '/chats/$threadId'
    | '/chats'
    | '/api/assets/$assetId'
    | '/api/auth/$'
    | '/api/reviews/sync'
    | '/api/card-chats/$threadId/stream'
  id:
    | '__root__'
    | '/'
    | '/progress'
    | '/settings'
    | '/topics'
    | '/chats/$threadId'
    | '/chats/'
    | '/api/assets/$assetId'
    | '/api/auth/$'
    | '/api/reviews/sync'
    | '/api/card-chats/$threadId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  TopicsRoute: typeof TopicsRoute
  ChatsThreadIdRoute: typeof ChatsThreadIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
  ApiAssetsAssetIdRoute: typeof ApiAssetsAssetIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiReviewsSyncRoute: typeof ApiReviewsSyncRoute
  ApiCardChatsThreadIdStreamRoute: typeof ApiCardChatsThreadIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$threadId': {
      id: '/chats/$threadId'
      path: '/chats/$threadId'
      fullPath: '/chats/$threadId'
      preLoaderRoute: typeof ChatsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$assetId': {
      id: '/api/assets/$assetId'
      path: '/api/assets/$assetId'
      fullPath: '/api/assets/$assetId'
      preLoaderRoute: typeof ApiAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/sync': {
      id: '/api/reviews/sync'
      path: '/api/reviews/sync'
      fullPath: '/api/reviews/sync'
      preLoaderRoute: typeof ApiReviewsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/card-chats/$threadId/stream': {
      id: '/api/card-chats/$threadId/stream'
      path: '/api/card-chats/$threadId/stream'
      fullPath: '/api/card-chats/$threadId/stream'
      preLoaderRoute: typeof ApiCardChatsThreadIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  TopicsRoute: TopicsRoute,
  ChatsThreadIdRoute: ChatsThreadIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
  ApiAssetsAssetIdRoute: ApiAssetsAssetIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiReviewsSyncRoute: ApiReviewsSyncRoute,
  ApiCardChatsThreadIdStreamRoute: ApiCardChatsThreadIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
