/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ApiAssetsAssetIdRouteImport } from './routes/api/assets/$assetId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiReviewsSyncRouteImport } from './routes/api/reviews/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsAssetIdRoute = ApiAssetsAssetIdRouteImport.update({
  id: '/api/assets/$assetId',
  path: '/api/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsSyncRoute = ApiReviewsSyncRouteImport.update({
  id: '/api/reviews/sync',
  path: '/api/reviews/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/reviews/sync': typeof ApiReviewsSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/reviews/sync': typeof ApiReviewsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/reviews/sync': typeof ApiReviewsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/progress'
    | '/settings'
    | '/topics'
    | '/api/assets/$assetId'
    | '/api/auth/$'
    | '/api/reviews/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/progress'
    | '/settings'
    | '/topics'
    | '/api/assets/$assetId'
    | '/api/auth/$'
    | '/api/reviews/sync'
  id:
    | '__root__'
    | '/'
    | '/progress'
    | '/settings'
    | '/topics'
    | '/api/assets/$assetId'
    | '/api/auth/$'
    | '/api/reviews/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  TopicsRoute: typeof TopicsRoute
  ApiAssetsAssetIdRoute: typeof ApiAssetsAssetIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiReviewsSyncRoute: typeof ApiReviewsSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$assetId': {
      id: '/api/assets/$assetId'
      path: '/api/assets/$assetId'
      fullPath: '/api/assets/$assetId'
      preLoaderRoute: typeof ApiAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/sync': {
      id: '/api/reviews/sync'
      path: '/api/reviews/sync'
      fullPath: '/api/reviews/sync'
      preLoaderRoute: typeof ApiReviewsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  TopicsRoute: TopicsRoute,
  ApiAssetsAssetIdRoute: ApiAssetsAssetIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiReviewsSyncRoute: ApiReviewsSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
